In [1]:
import numpy as np
import pandas as pd
import xarray as xr

## Does ICON data look like this? 


###  clat and clon are dimenstioned on ncells

In [3]:
ncells=10
ntime=2
da = xr.DataArray(np.random.random((ntime,ncells)),
                      coords={'time':pd.date_range('2010-01-01',periods=ntime),
                              'ncells':range(10,20),
                              'clat': ('ncells', range(-90,90,18)),
                              'clon': ('ncells', range(0,360,36))},
                 dims=('time','ncells'))


In [4]:
da  

<xarray.DataArray (time: 2, ncells: 10)>
array([[0.783802, 0.522054, 0.854826, 0.101406, 0.228865, 0.391967, 0.161783,
        0.6769  , 0.737813, 0.585983],
       [0.431944, 0.667856, 0.837359, 0.600827, 0.440348, 0.120492, 0.138685,
        0.51562 , 0.847286, 0.610812]])
Coordinates:
  * time     (time) datetime64[ns] 2010-01-01 2010-01-02
  * ncells   (ncells) int64 10 11 12 13 14 15 16 17 18 19
    clat     (ncells) int64 -90 -72 -54 -36 -18 0 18 36 54 72
    clon     (ncells) int64 0 36 72 108 144 180 216 252 288 324

# indexing based on clat and clon

In [5]:
minlat=0
maxlat=60
minlon=200
maxlon=280

In [6]:
da[:,((da.clon>minlon) & (da.clon<maxlon) & (da.clat>minlat) & (da.clat<maxlat) )]

<xarray.DataArray (time: 2, ncells: 2)>
array([[0.161783, 0.6769  ],
       [0.138685, 0.51562 ]])
Coordinates:
  * time     (time) datetime64[ns] 2010-01-01 2010-01-02
  * ncells   (ncells) int64 16 17
    clat     (ncells) int64 18 36
    clon     (ncells) int64 216 252

### xarray also has isin

In [7]:
xr.__version__

'0.10.4'

In [8]:
da[:,da.clon.isin([216,252])]

<xarray.DataArray (time: 2, ncells: 2)>
array([[0.161783, 0.6769  ],
       [0.138685, 0.51562 ]])
Coordinates:
  * time     (time) datetime64[ns] 2010-01-01 2010-01-02
  * ncells   (ncells) int64 16 17
    clat     (ncells) int64 18 36
    clon     (ncells) int64 216 252